---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concourse-webapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: concourse-webapi
    spec:
      containers:
      - name: concourse-webapi
        image: 10.203.188.244:30200/concourse-webapi:latest
        env:
          - name: CONCOURSE_BASIC_AUTH_USERNAME
            value: concourse
          - name: CONCOURSE_BASIC_AUTH_PASSWORD
            value: concourse
          - name: CONCOURSE_POSTGRES_DATA_SOURCE
            value: "postgres://concourse:concourse@$(CONCOURSE_POSTGRESQL_SERVICE_HOST):$(CONCOURSE_POSTGRESQL_SERVICE_PORT)/concourse?sslmode=disable"
          - name: CONCOURSE_EXTERNAL_URL
            value: http://$(CONCOURSE_WEBAPI_SERVICE_HOST):$(CONCOURSE_WEBAPI_SERVICE_PORT)
          - name: MY_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PEER_URL
            value: http://$(MY_IP):$(CONCOURSE_WEBAPI_SERVICE_PORT)
        ports:
          - containerPort: 8080
            name: atc
          - containerPort: 2222
            name: tsa
