---
apiVersion: v1
kind: Service
metadata:
  name: concourse-webapi
  labels:
    name: concourse-webapi
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      name: atc
    - port: 2222
      targetPort: 2222
      name: tsa
  selector:
    app: concourse-webapi
