---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concourse-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: concourse-postgresql
    spec:
      containers:
        - name: concourse-postgresql
          image: 10.203.188.244:30200/concourse-postgresql:latest
          env:
            - name: POSTGRES_USER
              value: concourse
            - name: POSTGRES_PASSWORD
              value: concourse
            - name: POSTGRES_DB
              value: concourse
            - name: PGDATA 
              value: '/database'
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /database
              name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}
