---
apiVersion: v1
kind: Service
metadata:
  name: concourse-postgresql
  labels:
    name: concourse-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: concourse-postgresql
