---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concourse-worker
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: concourse-worker
    spec:
      containers:
      - name: concourse-worker
        image: cicd-registry:30200/concourse-worker:latest
        env:
          - name: CONCOURSE_TSA_HOST
            value: $(CONCOURSE_WEBAPI_SERVICE_HOST)
        ports:
          - containerPort: 7777
            name: garden
          - containerPort: 7788
            name: baggageclaim
        securityContext:
          privileged: true
