---
apiVersion: v1
kind: Service
metadata:
  name: concourse-worker
  labels:
    name: concourse-worker
spec:
  selector:
    app: concourse-worker
  ports:
    - port: 7777
      targetPort: 7777
      name: garden
    - port: 7788
      targetPort: 7788
      name: baggageclaim
